/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.techducat.codeblocks.ui;

import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingUtilities;

/**
 *
 * @author odada
 */
public class SplashScreen extends javax.swing.JFrame {

    private Thread splashThreader;
    private AssemblyWorkbench mainWindow;
    private Image splashImage;

    /**
     * Creates new form SplashScreen
     * @param mainWindow
     */
    public SplashScreen(AssemblyWorkbench mainWindow) {
        try {
            Image image = ImageIO.read(this.getClass().getResource("/com/techducat/codeblocks/icons/codeblocks_icon.png"));
            splashImage = image.getScaledInstance(350, 350, Image.SCALE_SMOOTH);
            this.setIconImage(splashImage);
            initComponents();
            this.mainWindow = mainWindow;
            mainWindow.setVisible(false);
            implementThread();
        } catch (IOException ex) {
            Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.drawImage(splashImage, 0, 0, null);

    }

    // ping server to check server availability
    public static boolean ping(String url, int timeout) {
        url = url.replaceFirst("https", "http"); // Otherwise an exception may be thrown on invalid SSL certificates.

        try {
            HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
            connection.setConnectTimeout(timeout);
            connection.setReadTimeout(timeout);
            connection.setRequestMethod("HEAD");
            int responseCode = connection.getResponseCode();
            return (200 <= responseCode && responseCode <= 399);
        } catch (IOException exception) {
            return false;
        }
    }

    private void implementThread() {
      //final String [] strng = {"MySQL Database","Dependencies", "Configuration Files","ModuleTypes","Modules","Components","Libraries","User Authenticator","Models","Images"};

        splashThreader = new Thread(() -> {
            for (int i = 0; i <= 5; i++) {
                
                splashScreenProgressBar.setValue(i * 20);
                //splashScreenProgressBar.setString(i*10 +"% Loaded" +" ||    "+ "\tLoading " +strng[i]);
                if (i == 5) {
                    
                    mainWindow.init();
                    mainWindow.setVisible(true);
                    
                    SwingUtilities.windowForComponent(splashScreenProgressBar).setVisible(false);
                }
                
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException err) {
                }
                
            }
        });

        splashThreader.start();

    } //end implement thread method

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashScreenProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setUndecorated(true);
        setResizable(false);

        splashScreenProgressBar.setForeground(new java.awt.Color(101, 106, 114));
        splashScreenProgressBar.setBorderPainted(false);
        splashScreenProgressBar.setString("");
        splashScreenProgressBar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashScreenProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 359, Short.MAX_VALUE)
                .addComponent(splashScreenProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar splashScreenProgressBar;
    // End of variables declaration//GEN-END:variables
}
